/**
 * Vision
 * Sphereon Vision APIs
 *
 * OpenAPI spec version: 0.1
 * Contact: dev@sphereon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['SphereonSDKVision/ApiClient', 'SphereonSDKVision/model/VisionJob', 'SphereonSDKVision/model/VisionSettings', 'SphereonSDKVision/model/ErrorResponse', 'SphereonSDKVision/model/ClassificationResponse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/VisionJob'), require('../model/VisionSettings'), require('../model/ErrorResponse'), require('../model/ClassificationResponse'));
  } else {
    // Browser globals (root is window)
    if (!root.Vision) {
      root.Vision = {};
    }
    root.Vision.VisionApi = factory(root.Vision.ApiClient, root.Vision.VisionJob, root.Vision.VisionSettings, root.Vision.ErrorResponse, root.Vision.ClassificationResponse);
  }
}(this, function(ApiClient, VisionJob, VisionSettings, ErrorResponse, ClassificationResponse) {
  'use strict';

  /**
   * Vision service.
   * @module SphereonSDKVision/api/VisionApi
   * @version 0.1
   */

  /**
   * Constructs a new VisionApi. 
   * @alias module:SphereonSDKVision/api/VisionApi
   * @class
   * @param {module:SphereonSDKVision/ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:SphereonSDKVision/ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the createVisionJob operation.
     * @callback module:SphereonSDKVision/api/VisionApi~createVisionJobCallback
     * @param {String} error Error message, if any.
     * @param {module:SphereonSDKVision/model/VisionJob} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create a new vision job
     * Create a new job for the vision operation
     * @param {module:SphereonSDKVision/model/VisionSettings} visionSettings visionSettings
     * @param {module:SphereonSDKVision/api/VisionApi~createVisionJobCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:SphereonSDKVision/model/VisionJob}
     */
    this.createVisionJob = function(visionSettings, callback) {
      var postBody = visionSettings;

      // verify the required parameter 'visionSettings' is set
      if (visionSettings == undefined || visionSettings == null) {
        throw "Missing the required parameter 'visionSettings' when calling createVisionJob";
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['oauth2schema'];
      var contentTypes = ['application/json;charset=UTF-8'];
      var accepts = ['application/json;charset=UTF-8'];
      var returnType = VisionJob;

      return this.apiClient.callApi(
        '/vision/0.1/', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteVisionJob operation.
     * @callback module:SphereonSDKVision/api/VisionApi~deleteVisionJobCallback
     * @param {String} error Error message, if any.
     * @param {module:SphereonSDKVision/model/VisionJob} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete a vision job manually
     * Delete a vision job manually
     * @param {String} jobid jobid
     * @param {module:SphereonSDKVision/api/VisionApi~deleteVisionJobCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:SphereonSDKVision/model/VisionJob}
     */
    this.deleteVisionJob = function(jobid, callback) {
      var postBody = null;

      // verify the required parameter 'jobid' is set
      if (jobid == undefined || jobid == null) {
        throw "Missing the required parameter 'jobid' when calling deleteVisionJob";
      }


      var pathParams = {
        'jobid': jobid
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['oauth2schema'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json;charset=UTF-8'];
      var returnType = VisionJob;

      return this.apiClient.callApi(
        '/vision/0.1/{jobid}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getClassificationResult operation.
     * @callback module:SphereonSDKVision/api/VisionApi~getClassificationResultCallback
     * @param {String} error Error message, if any.
     * @param {module:SphereonSDKVision/model/ClassificationResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get classification result of a vision job
     * Get classification result of a vision job that completed the classification
     * @param {String} jobid jobid
     * @param {module:SphereonSDKVision/api/VisionApi~getClassificationResultCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:SphereonSDKVision/model/ClassificationResponse}
     */
    this.getClassificationResult = function(jobid, callback) {
      var postBody = null;

      // verify the required parameter 'jobid' is set
      if (jobid == undefined || jobid == null) {
        throw "Missing the required parameter 'jobid' when calling getClassificationResult";
      }


      var pathParams = {
        'jobid': jobid
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['oauth2schema'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json;charset=UTF-8'];
      var returnType = ClassificationResponse;

      return this.apiClient.callApi(
        '/vision/0.1/{jobid}/result', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getVisionJob operation.
     * @callback module:SphereonSDKVision/api/VisionApi~getVisionJobCallback
     * @param {String} error Error message, if any.
     * @param {module:SphereonSDKVision/model/VisionJob} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get a vision job
     * Get a Vision job
     * @param {String} jobid jobid
     * @param {module:SphereonSDKVision/api/VisionApi~getVisionJobCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:SphereonSDKVision/model/VisionJob}
     */
    this.getVisionJob = function(jobid, callback) {
      var postBody = null;

      // verify the required parameter 'jobid' is set
      if (jobid == undefined || jobid == null) {
        throw "Missing the required parameter 'jobid' when calling getVisionJob";
      }


      var pathParams = {
        'jobid': jobid
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['oauth2schema'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json;charset=UTF-8'];
      var returnType = VisionJob;

      return this.apiClient.callApi(
        '/vision/0.1/{jobid}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the submitVisionJob operation.
     * @callback module:SphereonSDKVision/api/VisionApi~submitVisionJobCallback
     * @param {String} error Error message, if any.
     * @param {module:SphereonSDKVision/model/VisionJob} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Start classification of a vision job
     * Start classification of a vision job
     * @param {String} jobid jobid
     * @param {module:SphereonSDKVision/model/VisionSettings} settings settings
     * @param {module:SphereonSDKVision/api/VisionApi~submitVisionJobCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:SphereonSDKVision/model/VisionJob}
     */
    this.submitVisionJob = function(jobid, settings, callback) {
      var postBody = settings;

      // verify the required parameter 'jobid' is set
      if (jobid == undefined || jobid == null) {
        throw "Missing the required parameter 'jobid' when calling submitVisionJob";
      }

      // verify the required parameter 'settings' is set
      if (settings == undefined || settings == null) {
        throw "Missing the required parameter 'settings' when calling submitVisionJob";
      }


      var pathParams = {
        'jobid': jobid
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['oauth2schema'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json;charset=UTF-8'];
      var returnType = VisionJob;

      return this.apiClient.callApi(
        '/vision/0.1/{jobid}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the uploadFile operation.
     * @callback module:SphereonSDKVision/api/VisionApi~uploadFileCallback
     * @param {String} error Error message, if any.
     * @param {module:SphereonSDKVision/model/VisionJob} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Upload an image for a vision job
     * Upload an image for a vision job. Processing will not be started yet.
     * @param {String} jobid jobid
     * @param {File} stream The binary image to upload for a vision job
     * @param {module:SphereonSDKVision/api/VisionApi~uploadFileCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:SphereonSDKVision/model/VisionJob}
     */
    this.uploadFile = function(jobid, stream, callback) {
      var postBody = null;

      // verify the required parameter 'jobid' is set
      if (jobid == undefined || jobid == null) {
        throw "Missing the required parameter 'jobid' when calling uploadFile";
      }

      // verify the required parameter 'stream' is set
      if (stream == undefined || stream == null) {
        throw "Missing the required parameter 'stream' when calling uploadFile";
      }


      var pathParams = {
        'jobid': jobid
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
        'stream': stream
      };

      var authNames = ['oauth2schema'];
      var contentTypes = ['multipart/form-data'];
      var accepts = ['application/json;charset=UTF-8'];
      var returnType = VisionJob;

      return this.apiClient.callApi(
        '/vision/0.1/{jobid}', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
