/**
 * Vision
 * Sphereon Vision APIs
 *
 * OpenAPI spec version: 0.2
 * Contact: dev@sphereon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['SphereonSDKVision/ApiClient', 'SphereonSDKVision/model/Credentials', 'SphereonSDKVision/model/Error', 'SphereonSDKVision/model/ErrorResponse', 'SphereonSDKVision/model/InputResource', 'SphereonSDKVision/model/Lifecycle', 'SphereonSDKVision/model/Result', 'SphereonSDKVision/model/StatusMessage', 'SphereonSDKVision/model/StorageSettings', 'SphereonSDKVision/model/StreamLocation', 'SphereonSDKVision/model/Tag', 'SphereonSDKVision/model/VendorResult', 'SphereonSDKVision/model/VisionJob', 'SphereonSDKVision/model/VisionSettings', 'SphereonSDKVision/api/VisionApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/Credentials'), require('./model/Error'), require('./model/ErrorResponse'), require('./model/InputResource'), require('./model/Lifecycle'), require('./model/Result'), require('./model/StatusMessage'), require('./model/StorageSettings'), require('./model/StreamLocation'), require('./model/Tag'), require('./model/VendorResult'), require('./model/VisionJob'), require('./model/VisionSettings'), require('./api/VisionApi'));
  }
}(function(ApiClient, Credentials, Error, ErrorResponse, InputResource, Lifecycle, Result, StatusMessage, StorageSettings, StreamLocation, Tag, VendorResult, VisionJob, VisionSettings, VisionApi) {
  'use strict';

  /**
   * Sphereon_Vision_APIs.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var Vision = require('SphereonSDKVision/index'); // See note below*.
   * var xxxSvc = new Vision.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new Vision.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['SphereonSDKVision/index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new Vision.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new Vision.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module SphereonSDKVision/index
   * @version 0.2
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:SphereonSDKVision/ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The Credentials model constructor.
     * @property {module:SphereonSDKVision/model/Credentials}
     */
    Credentials: Credentials,
    /**
     * The Error model constructor.
     * @property {module:SphereonSDKVision/model/Error}
     */
    Error: Error,
    /**
     * The ErrorResponse model constructor.
     * @property {module:SphereonSDKVision/model/ErrorResponse}
     */
    ErrorResponse: ErrorResponse,
    /**
     * The InputResource model constructor.
     * @property {module:SphereonSDKVision/model/InputResource}
     */
    InputResource: InputResource,
    /**
     * The Lifecycle model constructor.
     * @property {module:SphereonSDKVision/model/Lifecycle}
     */
    Lifecycle: Lifecycle,
    /**
     * The Result model constructor.
     * @property {module:SphereonSDKVision/model/Result}
     */
    Result: Result,
    /**
     * The StatusMessage model constructor.
     * @property {module:SphereonSDKVision/model/StatusMessage}
     */
    StatusMessage: StatusMessage,
    /**
     * The StorageSettings model constructor.
     * @property {module:SphereonSDKVision/model/StorageSettings}
     */
    StorageSettings: StorageSettings,
    /**
     * The StreamLocation model constructor.
     * @property {module:SphereonSDKVision/model/StreamLocation}
     */
    StreamLocation: StreamLocation,
    /**
     * The Tag model constructor.
     * @property {module:SphereonSDKVision/model/Tag}
     */
    Tag: Tag,
    /**
     * The VendorResult model constructor.
     * @property {module:SphereonSDKVision/model/VendorResult}
     */
    VendorResult: VendorResult,
    /**
     * The VisionJob model constructor.
     * @property {module:SphereonSDKVision/model/VisionJob}
     */
    VisionJob: VisionJob,
    /**
     * The VisionSettings model constructor.
     * @property {module:SphereonSDKVision/model/VisionSettings}
     */
    VisionSettings: VisionSettings,
    /**
     * The VisionApi service constructor.
     * @property {module:SphereonSDKVision/api/VisionApi}
     */
    VisionApi: VisionApi
  };

  return exports;
}));
