/*
 * Vision
 * Sphereon Vision APIs
 *
 * OpenAPI spec version: 0.2
 * Contact: dev@sphereon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.sphereon.sdk.vision.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.sphereon.sdk.vision.model.StorageSettings;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Vision settings
 */
@ApiModel(description = "Vision settings")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-01-09T14:08:09.031+01:00")
public class VisionSettings {
  /**
   * The provider of the storage.
   */
  @JsonAdapter(StorageProviderEnum.Adapter.class)
  public enum StorageProviderEnum {
    SUPPLIER("API_SUPPLIER");

    private String value;

    StorageProviderEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StorageProviderEnum fromValue(String text) {
      for (StorageProviderEnum b : StorageProviderEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<StorageProviderEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StorageProviderEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StorageProviderEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return StorageProviderEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("storageProvider")
  private StorageProviderEnum storageProvider = null;

  @SerializedName("storageSettings")
  private StorageSettings storageSettings = null;

  /**
   * Gets or Sets vendor
   */
  @JsonAdapter(VendorEnum.Adapter.class)
  public enum VendorEnum {
    GOOGLE_VISION("GOOGLE_VISION"),
    
    MS_AZURE_VISION("MS_AZURE_VISION"),
    
    CLARIFAI("CLARIFAI"),
    
    AWS("AWS");

    private String value;

    VendorEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static VendorEnum fromValue(String text) {
      for (VendorEnum b : VendorEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<VendorEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final VendorEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public VendorEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return VendorEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("vendor")
  private VendorEnum vendor = null;

  /**
   * Gets or Sets detectionTypes
   */
  @JsonAdapter(DetectionTypesEnum.Adapter.class)
  public enum DetectionTypesEnum {
    LABEL("LABEL"),
    
    TEXT("TEXT"),
    
    FACIAL("FACIAL"),
    
    LOGO("LOGO"),
    
    HANDWRITTEN("HANDWRITTEN");

    private String value;

    DetectionTypesEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static DetectionTypesEnum fromValue(String text) {
      for (DetectionTypesEnum b : DetectionTypesEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<DetectionTypesEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final DetectionTypesEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public DetectionTypesEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return DetectionTypesEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("detectionTypes")
  private List<DetectionTypesEnum> detectionTypes = null;

  public VisionSettings storageProvider(StorageProviderEnum storageProvider) {
    this.storageProvider = storageProvider;
    return this;
  }

   /**
   * The provider of the storage.
   * @return storageProvider
  **/
  @ApiModelProperty(value = "The provider of the storage.")
  public StorageProviderEnum getStorageProvider() {
    return storageProvider;
  }

  public void setStorageProvider(StorageProviderEnum storageProvider) {
    this.storageProvider = storageProvider;
  }

  public VisionSettings storageSettings(StorageSettings storageSettings) {
    this.storageSettings = storageSettings;
    return this;
  }

   /**
   * The settings of which storage is used to store images. The settings should be provided dependent on the StorageProvider setting.
   * @return storageSettings
  **/
  @ApiModelProperty(value = "The settings of which storage is used to store images. The settings should be provided dependent on the StorageProvider setting.")
  public StorageSettings getStorageSettings() {
    return storageSettings;
  }

  public void setStorageSettings(StorageSettings storageSettings) {
    this.storageSettings = storageSettings;
  }

  public VisionSettings vendor(VendorEnum vendor) {
    this.vendor = vendor;
    return this;
  }

   /**
   * Get vendor
   * @return vendor
  **/
  @ApiModelProperty(value = "")
  public VendorEnum getVendor() {
    return vendor;
  }

  public void setVendor(VendorEnum vendor) {
    this.vendor = vendor;
  }

  public VisionSettings detectionTypes(List<DetectionTypesEnum> detectionTypes) {
    this.detectionTypes = detectionTypes;
    return this;
  }

  public VisionSettings addDetectionTypesItem(DetectionTypesEnum detectionTypesItem) {
    if (this.detectionTypes == null) {
      this.detectionTypes = new ArrayList<>();
    }
    this.detectionTypes.add(detectionTypesItem);
    return this;
  }

   /**
   * The type of vision detection that should be performed on images. Different vendors support different detection types. All vendors support at least label detection.
   * @return detectionTypes
  **/
  @ApiModelProperty(value = "The type of vision detection that should be performed on images. Different vendors support different detection types. All vendors support at least label detection.")
  public List<DetectionTypesEnum> getDetectionTypes() {
    return detectionTypes;
  }

  public void setDetectionTypes(List<DetectionTypesEnum> detectionTypes) {
    this.detectionTypes = detectionTypes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VisionSettings visionSettings = (VisionSettings) o;
    return Objects.equals(this.storageProvider, visionSettings.storageProvider) &&
        Objects.equals(this.storageSettings, visionSettings.storageSettings) &&
        Objects.equals(this.vendor, visionSettings.vendor) &&
        Objects.equals(this.detectionTypes, visionSettings.detectionTypes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(storageProvider, storageSettings, vendor, detectionTypes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VisionSettings {\n");
    
    sb.append("    storageProvider: ").append(toIndentedString(storageProvider)).append("\n");
    sb.append("    storageSettings: ").append(toIndentedString(storageSettings)).append("\n");
    sb.append("    vendor: ").append(toIndentedString(vendor)).append("\n");
    sb.append("    detectionTypes: ").append(toIndentedString(detectionTypes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

