/* 
 * Vision
 *
 * Sphereon Vision APIs
 *
 * OpenAPI spec version: 0.1
 * Contact: dev@sphereon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sphereon.SDK.Vision.Api;
using Sphereon.SDK.Vision.Model;
using Sphereon.SDK.Vision.Client;
using System.Reflection;

namespace Sphereon.SDK.Vision.Test
{
    /// <summary>
    ///  Class for testing ClassificationResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ClassificationResponseTests
    {
        // TODO uncomment below to declare an instance variable for ClassificationResponse
        //private ClassificationResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ClassificationResponse
            //instance = new ClassificationResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ClassificationResponse
        /// </summary>
        [Test]
        public void ClassificationResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ClassificationResponse
            //Assert.IsInstanceOfType<ClassificationResponse> (instance, "variable 'instance' is a ClassificationResponse");
        }

        /// <summary>
        /// Test the property 'TagList'
        /// </summary>
        [Test]
        public void TagListTest()
        {
            // TODO unit test for the property 'TagList'
        }
        /// <summary>
        /// Test the property 'JobId'
        /// </summary>
        [Test]
        public void JobIdTest()
        {
            // TODO unit test for the property 'JobId'
        }
        /// <summary>
        /// Test the property 'Job'
        /// </summary>
        [Test]
        public void JobTest()
        {
            // TODO unit test for the property 'Job'
        }
        /// <summary>
        /// Test the property 'Errors'
        /// </summary>
        [Test]
        public void ErrorsTest()
        {
            // TODO unit test for the property 'Errors'
        }

    }

}
