/* 
 * Vision
 *
 * Sphereon Vision APIs
 *
 * OpenAPI spec version: 0.2
 * Contact: dev@sphereon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sphereon.SDK.Vision.Api;
using Sphereon.SDK.Vision.Model;
using Sphereon.SDK.Vision.Client;
using System.Reflection;

namespace Sphereon.SDK.Vision.Test
{
    /// <summary>
    ///  Class for testing StorageSettings
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class StorageSettingsTests
    {
        // TODO uncomment below to declare an instance variable for StorageSettings
        //private StorageSettings instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of StorageSettings
            //instance = new StorageSettings();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StorageSettings
        /// </summary>
        [Test]
        public void StorageSettingsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" StorageSettings
            //Assert.IsInstanceOfType<StorageSettings> (instance, "variable 'instance' is a StorageSettings");
        }

        /// <summary>
        /// Test the property 'Container'
        /// </summary>
        [Test]
        public void ContainerTest()
        {
            // TODO unit test for the property 'Container'
        }
        /// <summary>
        /// Test the property 'Lifecycle'
        /// </summary>
        [Test]
        public void LifecycleTest()
        {
            // TODO unit test for the property 'Lifecycle'
        }
        /// <summary>
        /// Test the property 'Credentials'
        /// </summary>
        [Test]
        public void CredentialsTest()
        {
            // TODO unit test for the property 'Credentials'
        }
        /// <summary>
        /// Test the property 'BackendType'
        /// </summary>
        [Test]
        public void BackendTypeTest()
        {
            // TODO unit test for the property 'BackendType'
        }
        /// <summary>
        /// Test the property 'Backend'
        /// </summary>
        [Test]
        public void BackendTest()
        {
            // TODO unit test for the property 'Backend'
        }

    }

}
