/* 
 * Vision
 *
 * Sphereon Vision APIs
 *
 * OpenAPI spec version: 0.2
 * Contact: dev@sphereon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sphereon.SDK.Vision.Api;
using Sphereon.SDK.Vision.Model;
using Sphereon.SDK.Vision.Client;
using System.Reflection;

namespace Sphereon.SDK.Vision.Test
{
    /// <summary>
    ///  Class for testing VisionSettings
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class VisionSettingsTests
    {
        // TODO uncomment below to declare an instance variable for VisionSettings
        //private VisionSettings instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of VisionSettings
            //instance = new VisionSettings();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of VisionSettings
        /// </summary>
        [Test]
        public void VisionSettingsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" VisionSettings
            //Assert.IsInstanceOfType<VisionSettings> (instance, "variable 'instance' is a VisionSettings");
        }

        /// <summary>
        /// Test the property 'StorageProvider'
        /// </summary>
        [Test]
        public void StorageProviderTest()
        {
            // TODO unit test for the property 'StorageProvider'
        }
        /// <summary>
        /// Test the property 'StorageSettings'
        /// </summary>
        [Test]
        public void StorageSettingsTest()
        {
            // TODO unit test for the property 'StorageSettings'
        }
        /// <summary>
        /// Test the property 'Vendor'
        /// </summary>
        [Test]
        public void VendorTest()
        {
            // TODO unit test for the property 'Vendor'
        }
        /// <summary>
        /// Test the property 'DetectionTypes'
        /// </summary>
        [Test]
        public void DetectionTypesTest()
        {
            // TODO unit test for the property 'DetectionTypes'
        }

    }

}
