/**
 * Vision
 * Sphereon Vision APIs
 *
 * OpenAPI spec version: 0.2
 * Contact: dev@sphereon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['SphereonSDKVision/ApiClient', 'SphereonSDKVision/model/StreamLocation'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./StreamLocation'));
  } else {
    // Browser globals (root is window)
    if (!root.Vision) {
      root.Vision = {};
    }
    root.Vision.InputResource = factory(root.Vision.ApiClient, root.Vision.StreamLocation);
  }
}(this, function(ApiClient, StreamLocation) {
  'use strict';




  /**
   * The InputResource model module.
   * @module SphereonSDKVision/model/InputResource
   * @version 0.2
   */

  /**
   * Constructs a new <code>InputResource</code>.
   * @alias module:SphereonSDKVision/model/InputResource
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>InputResource</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:SphereonSDKVision/model/InputResource} obj Optional instance to populate.
   * @return {module:SphereonSDKVision/model/InputResource} The populated <code>InputResource</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('streamLocation')) {
        obj['streamLocation'] = StreamLocation.constructFromObject(data['streamLocation']);
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
    }
    return obj;
  }

  /**
   * The storage location of the input file.
   * @member {module:SphereonSDKVision/model/StreamLocation} streamLocation
   */
  exports.prototype['streamLocation'] = undefined;
  /**
   * An id that links the file with the input and result.
   * @member {String} id
   */
  exports.prototype['id'] = undefined;



  return exports;
}));


