/**
 * Vision
 * Sphereon Vision APIs
 *
 * OpenAPI spec version: 0.2
 * Contact: dev@sphereon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['SphereonSDKVision/ApiClient', 'SphereonSDKVision/model/Tag'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Tag'));
  } else {
    // Browser globals (root is window)
    if (!root.Vision) {
      root.Vision = {};
    }
    root.Vision.VendorResult = factory(root.Vision.ApiClient, root.Vision.Tag);
  }
}(this, function(ApiClient, Tag) {
  'use strict';




  /**
   * The VendorResult model module.
   * @module SphereonSDKVision/model/VendorResult
   * @version 0.2
   */

  /**
   * Constructs a new <code>VendorResult</code>.
   * @alias module:SphereonSDKVision/model/VendorResult
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>VendorResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:SphereonSDKVision/model/VendorResult} obj Optional instance to populate.
   * @return {module:SphereonSDKVision/model/VendorResult} The populated <code>VendorResult</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('labels')) {
        obj['labels'] = ApiClient.convertToType(data['labels'], [Tag]);
      }
      if (data.hasOwnProperty('ocr')) {
        obj['ocr'] = ApiClient.convertToType(data['ocr'], [Tag]);
      }
    }
    return obj;
  }

  /**
   * labels that are predicted
   * @member {Array.<module:SphereonSDKVision/model/Tag>} labels
   */
  exports.prototype['labels'] = undefined;
  /**
   * ocr result
   * @member {Array.<module:SphereonSDKVision/model/Tag>} ocr
   */
  exports.prototype['ocr'] = undefined;



  return exports;
}));


